# theme: jekyll-theme-hacker
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: A machine learning engineer's homepage
description: It is not just about machine learning engineering ...
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
